### ISSUE TITLE
V1 - Clean up API

### ISSUE THREAD

**Issue by jfrolich** [jfrolich/authorize#6]
- [x] Authorize.Inline as default and only
- [x] `:unauthorized` => `:error`
- [x] `:undecided` => `:next`
- [x] Do not return schema but just a status
- [x] Update documentation
- [x] Publish 🎉

**Comment by jfrolich** [comment]
@sysashi @lrosa007 @goravbhootra @markman123, very interested in your opinion on the new API before I publish version 1!

**Comment by goravbhootra** [comment]
@jfrolich went thru the changes, looks good 😃 

I did a custom implementation for my current project. will open a new issue with code from the authorization file for your reference.

**Comment by jfrolich** [comment]
Logo 
![authorize-logo](https://user-images.githubusercontent.com/579279/39227502-8e7fbf56-488b-11e8-9711-5973fe1ba3aa.png)

**Comment by rvcas** [comment]
Looks great 😃

**Comment by jfrolich** [comment]
Haha added it here so I had an URL to use in README :)
