### ISSUE TITLE
Publish 1.0 to hex

### ISSUE THREAD

**Issue by gbogard** [jfrolich/authorize#8]
Hello

This is a very nice library. However, the latest version is not available on Hex. The latest version available on Hex is the ` 0.3.0` It would be nice to publish the lastest version.

Additionally, it would be nice to use tags on Github at each release so that I can add the project to my dependencies without having to use the `master`, just in case you publish a bug there by mistake.

**Comment by jfrolich** [comment]
Published 1.0. Will add tags for future releases!
